Sandbox tests

diff --git a/testfiles/support/engine b/testfiles/support/engine
--- a/testfiles/support/engine
+++ b/testfiles/support/engine
@@ -1,39 +1,70 @@
 #!/bin/bash
+# Called as one of
+#   $0 (dryrun|pdftex|xetex|luatex) ... '\input <job>.jam'
+#   $0 (dryrun|pdftex|xetex|luatex) ... '\input <job>.sh.jam'
+#   $0 dryrun ... '\input <job>.sh'
+#   $0 /path/a.tex
+# The `$0 dryrun ... '\input job[.sh].jam'` calls set the latex engine to $0,
+# accounting for the `$0 /path/a.tex` call.
+# The `$0 dryrun ... '\input job.sh'` calls just source job.sh and record the output.
+# The `$0 engine ... '\input job[.sh].jam'` calls have pdfjam run the appropriate engine
+# and output to $dir=job[.sh].d/engine.
+# A .jam file just contains pdfjam options.
+# A .sh.jam file is sourced and should make use of $pdfjam to produce output;
+# it may also use $job=job.sh and $dir=$job.d/engine.
 
 in=${!##\\input } # ${!#} is the last argument
-job=${in%.jam}
+job=${in%.*}
 out="$job.pdf"
+dir="$job.d/$1"
 
-tex=a
-case "$0" in
-	*engine-pdf|*engine-xe|*engine-lua)
-		tex=${0##*-}
-		latex=" --latex $(command -v "${tex}latex")"
-		;;
-	*engine) ;;
-	*) echo "name $0 unexpected"; exit 1
+testdir=$(realpath -- "$(dirname "$0")")
+export PATH="$testdir/../bin:$testdir"
+
+# Choose operation mode, set variables for setting pdfjam
+case "$1" in
+pdftex|xetex|luatex)
+	latex=$(command -v "${1%tex}latex") \
+		|| { echo Command "'${1%tex}latex'" not found; exit 1; }
+	preamble=" --preamble '"'\input{regression-test.tex}\AtBeginDocument{\START}'\'
+	;;
+dryrun)
+	latex=$(realpath "$0")
+	case "$in" in
+		*.sh) source "$in" | sed "s=$testdir=<TESTDIR>=g" >"$job.dryrun.log"; exit ;;
+		*.jam) ;;
+		*) echo "Wrong usage of $0"; exit 1 ;;
+	esac
+	;;
+*/a.tex|a.tex)
+	cp --verbose -- "$in" "$out"
+	exit
+	;;
+*) echo "Unknown engine '$1'"; exit 1 ;;
 esac
-dir="$tex/$job.d"
+pdfjam="./pdfjam --latex '$latex' --vanilla --builddir '$dir' --outfile '$out'$preamble"
 
-pdfjam="./pdfjam$latex --vanilla --builddir '$dir' --outfile '$out' --preamble '"\
-'\input{regression-test.tex}\AtBeginDocument{\START}'\'
-
+# Evaluate .jam files
 case "$job" in
 	*.sh) source "$in" ;;
 	*) eval "$pdfjam $(< "$in")" ;;
 esac
 
+[ "$1" = dryrun ] && exit
+
+# Rewrite log
+
 <"$dir/a.log" awk 'BEGIN{s=0}
-/^ *\[[0-9]+/{ORS=""}
+/^ *\[[0-9]/{ORS=""}
 /]$/{ORS="\n"}
-/]\(/{s=1}
+/] *\(/&&ORS=""{s=1}
 /\)/&&s=1{s=0;ORS="\n"}
 /^END-TEST-LOG$/{system("TZ=UTC pdfinfo '"$dir/a.pdf"'")}
 //' \
-	| sed '/^ *\[[0-9]\+/s/ //g
+	| sed '/^ *\[[0-9]/s/ //g
 		s/\.\([0-9]\{3\}\)[0-9]*pt/.\1pt/g
 		s/luatex\.def/pdftex.def/
-		/^<\(source-[0-9]*\|stdin\).pdf,/s/id=[0-9]*/id=00/
+		/^<\(source-[0-9]\+\|stdin\)\.pdf,/s/id=[0-9]*/id=00/
 		s/^\(Producer:        \).*$/\1TeXengine/
 		s/^\(File size:       \)[0-9]\{4,\} bytes/\10000 bytes/
 		' \
